name: Deploy Nginx with SBOM Generation

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Syft
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      # Step 3: Generate SBOM
      - name: Generate SBOM
        run: |
          chmod +x ./scripts/generate-sbom.sh  # Make sure the script is executable
          ./scripts/generate-sbom.sh

      # Step 4: Install Argo CD CLI
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd

      # Step 5: Deploy to Argo CD
      - name: Deploy to Argo CD
        run: |
          # Replace with your actual Argo CD server URL, username, and password
          argocd login https://b328-86-41-92-85.ngrok-free.app/ --username admin --password 9f60V43J-91W9RvN --insecure
          argocd app sync nginx-app  # Sync the application to deploy
