name: Deploy Nginx with SBOM Generation

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Syft for SBOM generation
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      # Step 3: Generate SBOM
      - name: Generate SBOM
        run: |
          chmod +x ./scripts/generate-sbom.sh  # Ensure the script is executable
          ./scripts/generate-sbom.sh            # Run the script to generate SBOM

      # Step 4: Install Argo CD CLI
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd  # Make the Argo CD CLI executable

      # Step 5: Deploy to Argo CD
      - name: Deploy to Argo CD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync nginx-app  # Sync the application to deploy
